uint64 timestamp		# time since system start (microseconds)

# Adaptive control
float32 u_x				# control input
float32 ym_x			# reference model
float32 u_y				# control input
float32 ym_y			# reference model

# Adaptive parameters
float32 the11_x 		# adaptive parameter theta_11
float32 the12_x 		# adaptive parameter theta_12
float32 the21_x 		# adaptive parameter theta_21
float32 the22_x 		# adaptive parameter theta_22
float32 the3_x 			# adaptive parameter theta_3
float32 c0_x 			# adaptive parameter c_0
float32 rho_x 			# adaptive parameter rho
float32 ua_x			# adaptive parameter performance
float32 the11_y 		# adaptive parameter theta_11
float32 the12_y 		# adaptive parameter theta_12
float32 the21_y 		# adaptive parameter theta_21
float32 the22_y 		# adaptive parameter theta_22
float32 the3_y 			# adaptive parameter theta_3
float32 c0_y 			# adaptive parameter c_0
float32 rho_y 			# adaptive parameter rho
float32 ua_y			# adaptive parameter performance
