#!/bin/sh
#
# @name Griffin
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

param set BAT_N_CELLS 6
param set BAT_A_PER_V 37.5
param set BAT_V_DIV 12.7
param set BAT_V_OFFS_CURR 0.525

param set IMU_GYRO_CUTOFF 80.0
param set MC_DTERM_CUTOFF 30.0

param set MC_ROLL_P 5
param set MC_ROLLRATE_P 0.2764
param set MC_ROLLRATE_I 0.0720
param set MC_ROLLRATE_D 0.0060
param set MC_ROLLRATE_FF 0.0
param set MC_ROLLRATE_MAX 120.0
param set MC_ACRO_R_MAX 120.0

param set MC_PITCH_P 5
param set MC_PITCHRATE_P 0.2764
param set MC_PITCHRATE_I 0.0720
param set MC_PITCHRATE_D 0.0060
param set MC_PITCHRATE_FF 0.0
param set MC_PITCHRATE_MAX 120.0
param set MC_ACRO_P_MAX 120.0

param set MC_YAW_P 0.8
param set MC_YAWRATE_P 0.3983
param set MC_YAWRATE_I 0.1593
param set MC_YAWRATE_D 0
param set MC_YAWRATE_FF 0.0
param set MC_YAWRATE_MAX 90.0
param set MC_ACRO_Y_MAX 45.0
param set MPC_MAN_Y_MAX 45.0

param set MPC_TILTMAX_AIR 30.0
param set MPC_MAN_TILT_MAX 30.0

param set MPC_VELD_LP 5.0

param set MPC_X_P 0.73254
param set MPC_X_I 0.0
param set MPC_Y_P 0.73254
param set MPC_Y_I 0.0
param set MPC_X_VEL_P 0.1615
param set MPC_X_VEL_I 0.0319
param set MPC_X_VEL_D 0.0106
param set MPC_Y_VEL_P 0.1615
param set MPC_Y_VEL_I 0.0319
param set MPC_Y_VEL_D 0.0106

param set MPC_Z_P 1.0
param set MPC_Z_VEL_P 0.1549
param set MPC_Z_VEL_I 0.0279
param set MPC_Z_VEL_D 0

param set MPC_XY_CRUISE 12.0
param set MPC_XY_VEL_MAX 12.0
param set MPC_VEL_MANUAL 12.0
param set MPC_Z_VEL_MAX_DN 1.0
param set MPC_Z_VEL_MAX_UP 3.0

param set MIS_TAKEOFF_ALT 2.5
param set RTL_DESCEND_ALT 10.0
param set RTL_RETURN_ALT 10.0
param set MPC_TKO_RAMP_T 0.0

param set PWM_MAX 1720
param set PWM_MIN 1000

param set MPC_THR_CURVE 1
param set MPC_THR_HOVER 0.296875
param set MPC_THR_MAX 1.0
param set MPC_THR_MIN 0.08
param set MPC_MANTHR_MIN 0.08

param set PWM_MAIN_SCALE1 1.01315789
param set PWM_MAIN_SCALE2 1.00442478
param set PWM_MAIN_SCALE3 1.00074019
param set PWM_MAIN_SCALE4 1.00000000

# Adaptive
param set MPC_X_ADAPTIVE 0

param set MRAC_WN 1.2
param set MRAC_ZETA 0.8
param set MRAC_ZERO 5
param set MRAC_SGN_K 1
param set MRAC_LAMBDA 100
param set MRAC_GAIN_W11 150
param set MRAC_GAIN_W12 150
param set MRAC_GAIN_W21 150
param set MRAC_GAIN_W22 750
param set MRAC_GAIN_YP 0.03
param set MRAC_GAIN_R 0.06
param set MRAC_GAIN_RHO 0.03
param set MRAC_INIT_THE11 105
param set MRAC_INIT_THE12 490.1934
param set MRAC_INIT_THE21 377.0628
param set MRAC_INIT_THE22 1821.7
param set MRAC_INIT_THE3 -3.6538
param set MRAC_INIT_C0 0.0103
param set MRAC_ADAP_MARGIN 0.025
param set MRAC_LEAKAGE 0.001

# PID X Adaptive
param set MPC_ADAPTIVE_X_P 0.3
param set MPC_ADAPTIVE_X_I 0.001

set MIXER griffin
