#!/bin/sh
#
# @name Griffin with Payload
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

# Use GRIFFIN parameters
sh /etc/init.d-posix/4960_griffin

# PID XY Payload
param set MPC_X_P 0.3
param set MPC_Y_P 0.4
param set MPC_X_VEL_P 0.04
param set MPC_X_VEL_I 0.006
param set MPC_X_VEL_D 0.0133
param set MPC_Y_VEL_P 0.048
param set MPC_Y_VEL_I 0.008
param set MPC_Y_VEL_D 0.002

# Adaptive
param set MPC_X_ADAP_EN 0

param set MPC_MRAC_WN 0.8
param set MPC_MRAC_SGN_K 1
param set MPC_MRAC_LMBDWN 50
param set MPC_MRAC_LMBDZT 0.9
param set MPC_MRAC_UP_NORM 125.5680
param set MPC_MRAC_GAINW11 0
param set MPC_MRAC_GAINW12 0
param set MPC_MRAC_GAINW21 0
param set MPC_MRAC_GAINW22 0
param set MPC_MRAC_GAINYP 0 #10000
param set MPC_MRAC_GAINR 0 #1250
param set MPC_MRAC_GAINRO 0 #2
param set MPC_MRACI_THE11 90
param set MPC_MRACI_THE12 2499
param set MPC_MRACI_THE21 25204
param set MPC_MRACI_THE22 1012500
param set MPC_MRACI_THE3 -408.6
param set MPC_MRACI_C0 3.6

# PID X Adaptive
param set MPC_ADAP_X_P 0.25
