#!/bin/sh
#
# @name Griffin with Payload
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

# Use GRIFFIN parameters
sh /etc/init.d-posix/4960_griffin

# PID XY Payload
param set MPC_X_P 0.35
param set MPC_Y_P 0.35
param set MPC_X_VEL_P 0.048
param set MPC_X_VEL_I 0.008
param set MPC_X_VEL_D 0.002
param set MPC_Y_VEL_P 0.048
param set MPC_Y_VEL_I 0.008
param set MPC_Y_VEL_D 0.002

# Adaptive
param set MPC_X_ADAP_EN 0
param set MPC_Y_ADAP_EN 0

param set MPC_MRAC_WN 0.8
param set MPC_MRAC_SGN_K 1
param set MPC_MRAC_LMBDWN 8
param set MPC_MRAC_LMBDZT 0.9
param set MPC_MRAC_UP_NORM 125.5680
param set MPC_MRAC_GAINW11 0
param set MPC_MRAC_GAINW12 0
param set MPC_MRAC_GAINW21 0
param set MPC_MRAC_GAINW22 0
param set MPC_MRAC_GAINYP 2000
param set MPC_MRAC_GAINR 250
param set MPC_MRAC_GAINRO 0.2
param set MPC_MRACI_THE11 14.4
param set MPC_MRACI_THE12 64
param set MPC_MRACI_THE21 645.12
param set MPC_MRACI_THE22 4147.2
param set MPC_MRACI_THE3 -68.4
param set MPC_MRACI_C0 3.6
param set MPC_MRAC_LEAK11B 10000000
param set MPC_MRAC_LEAK12B 10000000
param set MPC_MRAC_LEAK21B 10000000
param set MPC_MRAC_LEAK22B 10000000
param set MPC_MRAC_LEAK3B 72.2250
param set MPC_MRAC_LEAK4B 7.4250
param set MPC_MRAC_LEAK11G 0
param set MPC_MRAC_LEAK12G 0
param set MPC_MRAC_LEAK21G 0
param set MPC_MRAC_LEAK22G 0
param set MPC_MRAC_LEAK3G 0.00002
param set MPC_MRAC_LEAK4G 0.00002
param set MPC_MRAC_P_TAU 0.4
param set MPC_MRAC_BOUND11 10000000
param set MPC_MRAC_BOUND12 10000000
param set MPC_MRAC_BOUND21 10000000
param set MPC_MRAC_BOUND22 10000000
param set MPC_MRAC_BOUND3 -79.65
param set MPC_MRAC_BOUND4 9.9

# PID X Adaptive
param set MPC_ADAP_X_P 0.25
param set MPC_ADAP_Y_P 0.25
